-- Authentication models: User, Account, Session, VerificationToken.
--
-- ============================================================================
-- HOW THIS WENT MISSING
-- ============================================================================
-- Same cause as 20260727120000_add_geo_targeting: applied to the live database
-- with `prisma db push`, which changes the database without recording a
-- migration. But this one is far more serious than the geo columns.
--
-- The nine original migrations create only SIX of the ten models in
-- schema.prisma:
--
--   created by migrations : Domain, Page, ContentBlock, DomainCategory,
--                           Table, RichTextContent
--   MISSING               : User, Account, Session, VerificationToken
--
-- So `prisma migrate deploy` against a fresh database produced a schema with no
-- User table at all. Consequences on that database:
--
--   * nobody can log in — `authorize()` queries a table that does not exist
--   * NextAuth's adapter models are absent, so the whole auth flow throws
--   * `prisma/seed-admin.ts` cannot create the first admin
--
-- The public site would 500 for a different reason too (geo columns), but even
-- after fixing that, the admin panel would have been permanently unreachable.
--
-- ============================================================================
-- HOW THIS FILE WAS PRODUCED — NOT HAND-WRITTEN
-- ============================================================================
-- Generated by Prisma itself, so it is guaranteed to match what `schema.prisma`
-- expects rather than being a close approximation:
--
--   npx prisma migrate diff \
--     --from-migrations prisma/migrations \
--     --to-schema-datamodel prisma/schema.prisma \
--     --shadow-database-url <empty db on a throwaway Neon branch> \
--     --script
--
-- `--from-migrations` replays every existing migration into an empty shadow
-- database, then diffs the result against schema.prisma. Whatever comes out is
-- exactly what the migration history was missing. Re-running that command after
-- adding this file returns an empty diff.
--
-- ============================================================================
-- MARKED `--applied` ON EXISTING DATABASES, NOT EXECUTED
-- ============================================================================
-- Production and the rehearsal branch already have these tables, and they hold
-- real admin accounts. Running this SQL there would fail on
-- "relation User already exists". It is registered with
--     npx prisma migrate resolve --applied 20260727130000_add_auth_models
-- which writes a history row and executes nothing. It runs for real only on a
-- genuinely new database.
--
-- Note `"updatedAt" TIMESTAMP(3) NOT NULL` with no DEFAULT — that is how Prisma
-- represents `@updatedAt`. Relevant to the pending Page/Domain `updatedAt` work:
-- on a table that already has rows, that exact form cannot be added directly and
-- needs a backfill first.

-- CreateTable
CREATE TABLE "public"."User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "password" TEXT NOT NULL,
    "isAdmin" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "lastLoginAt" TIMESTAMP(3),
    "createdBy" TEXT,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "public"."User"("email");

-- CreateIndex
CREATE INDEX "User_email_idx" ON "public"."User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "public"."Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "public"."Session"("sessionToken");

-- CreateIndex
CREATE INDEX "Session_sessionToken_idx" ON "public"."Session"("sessionToken");

-- CreateIndex
CREATE INDEX "Session_userId_idx" ON "public"."Session"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "public"."VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "public"."VerificationToken"("identifier", "token");

-- AddForeignKey
ALTER TABLE "public"."User" ADD CONSTRAINT "User_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
